### ISSUE TITLE
Found no configured JSON fields to transform

### ISSUE THREAD

**Issue by christopherplain** [mirabilio/gatsby-plugin-json-remark#8]
I'm getting the following error consistently after the first run of `gatsby develop` when using the Tina Grande Gatsby starter:

```warn 'gatsby-plugin-json-remark' found no configured JSON fields to transform.```

This error appears to be reproducible whether cloning the repo or installing the starter via `gatsby new tina-starter-grande https://github.com/tinacms/tina-starter-grande`.

Steps to reproduce:
1. Clone repo or install starter via Gatsby CLI.
2. Start development server (`gatsby develop`).
3. Stop development server (`^C`).
4. Start development server (`gatsby develop`).

The error will not occur the first time the development server is started. All subsequent runs, however, will produce the error until the environment is cleaned (`gatsby clean`).

**Comment by mirabilio** [comment]
@christopherplain Thanks for pointing this out. I will take a look asap. Is it causing any issues with deployment? PS pls upgrade to v1.1.4. It contains critical bug fixes.

**Comment by christopherplain** [comment]
@mirabilio, apologies for the belated response. I don't use `gatsby build` locally. I deploy to Netlify via the GitHub integration. I haven't seen any issues deploying to Netlify. Though, that could be because I haven't enabled the incremental build plugin.

**Comment by RDjarbeng** [comment]
**I also have this problem.**
I have followed the steps in the tutorial, but still see no change to the markdown content stored as a string in my JSON files or in graphql. 
These are the warnings I receive:

warning The gatsby-plugin-json-remark plugin has generated no Gatsby nodes. Do you need it?
warning gatsby-plugin-json-remark found no configured JSON fields to transform.

I have tried gatsby clean as well as different options for the path property all to no avail.

My package.json
`"gatsby-plugin-json-remark": "^1.1.5",`

Inside gatsby-config.js

```
module.exports = {
  plugins: [
    'gatsby-transformer-remark',
    {
      resolve: "gatsby-source-filesystem",
      options: {
        name: 'src',
        path: `${__dirname}/src/`
      },
    },
    `gatsby-plugin-netlify-cms`,
    {
      resolve: `gatsby-plugin-json-remark`,
      options: {
        paths: [
          `${__dirname}/src/content/`,//I have a single json file highlightData.json inside this folder
        ], // Process all JSON files in these directories.
        fieldNameBlacklist: [
          "id",
          "children",
          "parent",
          "fields",
          "internal",
          "path",
          "template",
        ],
      },
    },
  ],
}
```
Iinside src/content/HighlightData.json
```
{"paragraph1": "To build a **World**-class listed.",
  "paragraph2": "blah  blah ",...
}
```
_Notice the bold markdown syntax for 'world'._

I have verified the file paths point to the file by logging from this file.
And even tried changing the path option to
```
 paths: [
          `${__dirname}/content/`,//I have a single json file highlightData.json inside this folder
        ],
```
And also to
```
 paths: [
          `${__dirname}/src/content/highlightData.json`,//This still does not work
        ],
```

**Comment by nasnyder91** [comment]
I am having the same issue as RDjarbeng
